name: Build Release

on: 
  workflow_dispatch:
  push:
    branches: main
    paths: ./

env:
  packageName: "lyuma.av3emulator"
  packagePath: "Packages/lyuma.av3emulator"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with: 
            path: "./package.json"
            prop_path: "version"
    
      - name: Set Environment Variables
        run: |
          echo "zipFile=${{ env.packageName }}-${{ steps.version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "unityPackage=${{ env.packageName }}-${{ steps.version.outputs.prop }}.unitypackage" >> $GITHUB_ENV
          
      
      - name: Create directory and move files
        run: |
          mkdir -p ${{env.packagePath}}
          rsync -r --exclude="${{ env.packagePath }}" ./ "${{ env.packagePath }}"/
        
      - name: Create Zip
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          directory: "Packages/${{env.packageName}}/"
          filename: "../../${{env.zipFile}}" # make the zip file two directories up, since we start two directories in above
      
      - run: find "${{env.packagePath}}" -name \*.meta >> metaList
          
      - name: Create UnityPackage
        uses: pCYSl5EDgo/create-unitypackage@v1.1.1
        with:
          package-path: ${{ env.unityPackage }}
          include-files: metaList
        
        
      - name: Make Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: "Av3Emulator ${{ steps.version.outputs.prop }}"
          tag_name: ${{ steps.version.outputs.prop }}
          files: |
            ${{ env.zipFile }}
            ${{ env.unityPackage }}
            ./package.json
